// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkdbxokzjgenvexurgtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZGJ4b2t6amdlbnZleHVyZ3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTgyNDEsImV4cCI6MjA1OTU3NDI0MX0.zSsjsjtDotSDi4cKHCKorO4z6fnqlaqmByVQR8YgYbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);